name: BattleBox
version: '${project.version}'
main: io.github.cardsandhuskers.battlebox.BattleBox
api-version: 1.19
depend: [Teams]
softdepend: [Multiverse-Core, PlaceholderAPI]
commands:
  startBattleBox:
    description: starts the game
    command: /<command> [multiplier]
  setBattleboxSpawn:
    description: sets point where players enter the world
    command: /<command>
  setBattleboxArena:
    description: sets the center point of the specified arena
    command: /<command> [arena]
  setBattleBoxArenaSpawn:
    description: sets the spawn point for the specified arena and team
    command: /<command> [arena] [side]
  setBattleBoxKitSpawn:
    description: sets the spawn point for the kit selection room for the specified arena and team
    command: /<command> [arena] [side]
  setLobby:
    description: sets the location of the lobby
    command: /<command>
  setBattleboxArenaWall:
    description: sets the location of the bottom center block of the drop wall
    usage: /<command> [arena] [side]
  cancelBattlebox:
    description: cancels a game
    usage: /<command>
  reloadBattlebox:
    description: reloads the game config
    usage: /<command>
